version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/travis/build
    overwrite: yes
    
hook:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root
