version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app/travis/build
    overwrite: yes
    
hook:
  ApplicationStart:
    - location: /home/ec2-user/app/travis/build/scripts/deploy.sh
      timeout: 60
      runas: ec2-user
